<?php

$config['categories'] = array(

	1 	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU SERTAR',
					'title_en' 	=> 'GATE VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	2 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 1,
				),
	3 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-sertar-api-fonta',
					'link_en' 	=> 'gate-valves-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 2,
				),
	4 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-sertar-api-otel',
					'link_en' 	=> 'gate-valves-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 2,
				),
	5 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-sertar-api-inox',
					'link_en' 	=> 'gate-valves-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 2,
				),
	6 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 1,
				),
	7 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-sertar-din-fonta',
					'link_en' 	=> 'gate-valves-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 6,
				),
	8 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-sertar-din-otel',
					'link_en' 	=> 'gate-valves-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 6,
				),
	9 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-sertar-din-inox',
					'link_en' 	=> 'gate-valves-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 6,
				),


	21 	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU VENTIL',
					'title_en' 	=> 'GLOBE VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	22 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 21,
				),
	23 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-ventil-api-fonta',
					'link_en' 	=> 'globe-valves-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 22,
				),
	24 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-ventil-api-otel',
					'link_en' 	=> 'globe-valves-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 22,
				),
	25 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-ventil-api-inox',
					'link_en' 	=> 'globe-valves-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 22,
				),
	26 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 21,
				),                    
	27 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-ventil-din-fonta',
					'link_en' 	=> 'globe-valves-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 26,
				),
	28 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-ventil-din-otel',
					'link_en' 	=> 'globe-valves-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 26,
				),
	29 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-ventil-din-inox',
					'link_en' 	=> 'globe-valves-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 26,
				),



	31 	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU SFERA',
					'title_en' 	=> 'BALL VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,					
				),
	32 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 31,
				),
	33 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-sfera-api-fonta',
					'link_en' 	=> 'ball-valves-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 32,
				),
	34 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-sfera-api-otel',
					'link_en' 	=> 'ball-valves-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 32,
				),
	35 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-sfera-api-inox',
					'link_en' 	=> 'ball-valves-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 32,
				),
	36 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 31,
				),                    
	37 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-inchidere-sfera-din-fonta',
					'link_en' 	=> 'ball-valves-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 36,
				),
	38 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-inchidere-sfera-din-otel',
					'link_en' 	=> 'ball-valves-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 36,
				),
	39 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-inchidere-sfera-din-inox',
					'link_en' 	=> 'ball-valves-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 36,
				),


	41 	=> array(	'title_ro' 	=> 'ROBINETE CLAPA FLUTURE',
					'title_en' 	=> 'BUTTERFLY VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	42 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 41,
				),
	43 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-clapa-fluture-api-fonta',
					'link_en' 	=> 'butterfly-vales-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 42,
				),
	44 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-clapa-fluture-api-otel',
					'link_en' 	=> 'butterfly-vales-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 42,
				),
	45 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-clapa-fluture-api-inox',
					'link_en' 	=> 'butterfly-vales-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 42,
				),
	46 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 41,
				),                    
	47 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-clapa-fluture-din-fonta',
					'link_en' 	=> 'butterfly-vales-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 46,
				),
	48 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-clapa-fluture-din-otel',
					'link_en' 	=> 'butterfly-vales-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 46,
				),
	49 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-clapa-fluture-din-inox',
					'link_en' 	=> 'butterfly-vales-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 46,
				),


	51 	=> array(	'title_ro' 	=> 'ROBINETE RETINERE CU CLAPA',
					'title_en' 	=> 'SWING CHECK VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	52 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 51,
				),
	53 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-retinere-clapa-api-fonta',
					'link_en' 	=> 'swing-check-valvles-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 52,
				),
	54 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-retinere-clapa-api-otel',
					'link_en' 	=> 'swing-check-valvles-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 52,
				),
	55 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-retinere-clapa-api-inox',
					'link_en' 	=> 'swing-check-valvles-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 52,
				),
	56 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 51,
				),                    
	57 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-retinere-clapa-din-fonta',
					'link_en' 	=> 'swing-check-valvles-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 56,
				),
	58 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-retinere-clapa-din-otel',
					'link_en' 	=> 'swing-check-valvles-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 56,
				),
	59 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-retinere-clapa-din-inox',
					'link_en' 	=> 'swing-check-valvles-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 52,
				),

	61 	=> array(	'title_ro' 	=> 'ROBINETE RETINERE CU VENTIL',
					'title_en' 	=> 'LIFT TYPE CHECK VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	62 	=> array(	'title_ro' 	=> 'STANDARD API',
					'title_en' 	=> 'API STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 61,
				),
	63 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-retinere-ventil-api-fonta',
					'link_en' 	=> 'lift-type-check-valves-api-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 62,
				),
	64 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-retinere-ventil-api-otel',
					'link_en' 	=> 'lift-type-check-valves-api-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 62,
				),
	65 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-retinere-ventil-api-inox',
					'link_en' 	=> 'lift-type-check-valves-api-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 62,
				),
	66 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 61,
				),                    
	67 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-retinere-ventil-din-fonta',
					'link_en' 	=> 'lift-type-check-valves-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 66,
				),
	68 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'robinete-retinere-ventil-din-otel',
					'link_en' 	=> 'lift-type-check-valves-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 66,
				),
	69 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'robinete-retinere-ventil-din-inox',
					'link_en' 	=> 'lift-type-check-valves-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 66,
				),


	71 	=> array(	'title_ro' 	=> 'ROBINETE RETINERE CU BILA',
					'title_en' 	=> 'BALL CHECK VALVES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	72 	=> array(	'title_ro' 	=> 'STANDARD DIN',
					'title_en' 	=> 'DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 71,
				),
	73 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'robinete-retinere-bila-din-fonta',
					'link_en' 	=> 'ball-check-valves-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 72,
				),


	80 	=> array(	'title_ro' 	=> 'FILTRE DE IMPURITATI',
					'title_en' 	=> 'STRAINERS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	81 	=> array(	'title_ro' 	=> 'FILTRE TIP Y STANDARD ANSI',
					'title_en' 	=> 'Y STRAINERS ANSI STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 80,
				),
	82 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-ansi-fonta',
					'link_en' 	=> 'strainers-y-strainers-ansi-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 81,
				),
	83 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-ansi-otel',
					'link_en' 	=> 'strainers-y-strainers-ansi-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 81,
				),
	84 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-ansi-inox',
					'link_en' 	=> 'strainers-y-strainers-ansi-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 81,
				),
	85 	=> array(	'title_ro' 	=> 'FILTRE TIP Y STANDARD DIN',
					'title_en' 	=> 'Y STRAINERS DIN STANDARD',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 80,
				),
	86 	=> array(	'title_ro' 	=> 'FONTA',
					'title_en' 	=> 'CAST IRON',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-din-fonta',
					'link_en' 	=> 'strainers-y-strainers-din-cast-iron',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 85,
				),
	87 	=> array(	'title_ro' 	=> 'OTEL',
					'title_en' 	=> 'CARBON STEEL',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-din-otel',
					'link_en' 	=> 'strainers-y-strainers-din-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 85,
				),
	88 	=> array(	'title_ro' 	=> 'INOX',
					'title_en' 	=> 'STAINLESS STEEL',
					'link_ro' 	=> 'filtre-impuritati-filtre-tip-y-din-inox',
					'link_en' 	=> 'strainers-y-strainers-din-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 85,
				),
				
	89 	=> array(	'title_ro' 	=> 'SORBURI SIMPLE',
					'title_en' 	=> 'STRAINER BASKET',
					'link_ro' 	=> 'filtre-impuritati-sorburi-simple',
					'link_en' 	=> 'strainers-strainer-basket',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 80,
				),
	90 	=> array(	'title_ro' 	=> 'SORBURI CU CLAPA',
					'title_en' 	=> 'CHECK VALVE STRAINER BASKET',
					'link_ro' 	=> 'filtre-impuritati-sorburi-clapa',
					'link_en' 	=> 'strainers-check-valve-strainer-basket',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 80,					
				),


	91 	=> array(	'title_ro' 	=> 'HIDRANTI',
					'title_en' 	=> 'HYDRANTS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,					
				),
	92 	=> array(	'title_ro' 	=> 'HIDRANTI SUBTERANI',
					'title_en' 	=> 'UNDERGROUND HYDRANTS',
					'link_ro' 	=> 'hidranti-subterani',
					'link_en' 	=> 'underground-hydrants',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 91,
				),
	93 	=> array(	'title_ro' 	=> 'HIDRANTI SUPRATERANI',
					'title_en' 	=> 'ABOVE GROUND HYDRANTS',
					'link_ro' 	=> 'hidranti-supraterani',
					'link_en' 	=> 'above-ground-hydrants',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 91,
				),

	94 	=> array(	'title_ro' 	=> 'ACCESORII',
					'title_en' 	=> 'ACCESORIES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 91,
				),

	95 	=> array(	'title_ro' 	=> 'COTURI HIDRANT',
					'title_en' 	=> 'DUCK-FOOT BEND',
					'link_ro' 	=> 'hidranti-coturi-hidrant',
					'link_en' 	=> 'hydrants-duck-foot-bend',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 94,
				),

	96 	=> array(	'title_ro' 	=> 'CUTII HIDRANT',
					'title_en' 	=> 'STREET BOXES',
					'link_ro' 	=> 'hidranti-cutii-hidrant',
					'link_en' 	=> 'hydrants-street-boxes',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 94,
				),
				
	101 => array(	'title_ro' 	=> 'ECHIPAMENTE PENTRU RETELE DE APA',
					'title_en' 	=> 'EQUIPMENTS FOR WATER SUPPLY SYSTEMS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	102 => array(	'title_ro' 	=> 'ROBINETE DE REGLARE HIDRAULICA',
					'title_en' 	=> 'HYDRAULIC THROTTLE VALVE',
					'link_ro' 	=> 'robinete-reglare-hidraulica',
					'link_en' 	=> 'hydraulic-throttle-valve',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),
	103 => array(	'title_ro' 	=> 'ROBINETE DE AERISIRE-DEZAERISIRE',
					'title_en' 	=> 'AIR RELIEF VALVES',
					'link_ro' 	=> 'robinete-aerisire-dezaerisire',
					'link_en' 	=> 'air-relief-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),			

	104 => array(	'title_ro' 	=> 'SUPAPE DE DESCARCARE',
					'title_en' 	=> 'DISCHARGE VALVE',
					'link_ro' 	=> 'supape-descarcare',
					'link_en' 	=> 'discharge-valve',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),			

	105 => array(	'title_ro' 	=> 'VANE AUTOMATE DE CONTROL',
					'title_en' 	=> 'AUTOMATIC CONTROL VALVES',
					'link_ro' 	=> 'vane-automate-control',
					'link_en' 	=> 'automatic-control-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),			

	106 => array(	'title_ro' 	=> 'CISMELE STRADALE',
					'title_en' 	=> 'STREET FOUNTAINS',
					'link_ro' 	=> 'cismele-stradale',
					'link_en' 	=> 'street-fountains',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),			

	107 => array(	'title_ro' 	=> 'CONTOARE DE APA',
					'title_en' 	=> 'WATER METERS',
					'link_ro' 	=> 'contoare-apa',
					'link_en' 	=> 'water-meters',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 101,
				),			


	111 => array(	'title_ro' 	=> 'ECHIPAMENTE PENTRU ABUR',
					'title_en' 	=> 'EQUIPMENTS FOR STEAM',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	112 => array(	'title_ro' 	=> 'OALE DE CONDENS',
					'title_en' 	=> 'STEAM TRAPS',
					'link_ro' 	=> 'oale-condens',
					'link_en' 	=> 'steam-traps',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 111,
				),
	113 => array(	'title_ro' 	=> 'SEPARATOARE TERMODINAMICE',
					'title_en' 	=> 'THERMODYNAMIC SEPARATORS',
					'link_ro' 	=> 'separatoare-termodinamice',
					'link_en' 	=> 'thermodynamic-separators',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 111,
				),			
	114 => array(	'title_ro' 	=> 'REGULATOARE DE PRESIUNE',
					'title_en' 	=> 'PRESSURE REDUCING VALVE',
					'link_ro' 	=> 'regulatoare-presiune',
					'link_en' 	=> 'pressure-reducing-valve',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 111,
				),			
	115 => array(	'title_ro' 	=> 'SUPAPE DE SIGURANTA',
					'title_en' 	=> 'SAFETY VALVES',
					'link_ro' 	=> 'supape-siguranta',
					'link_en' 	=> 'safety-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 111,
				),	
				
				
	161	=> array(	'title_ro' 	=> 'ECHIPAMENTE PENTRU FORAJ',
					'title_en' 	=> 'WELLHEAD EQUIPMENTS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	162 => array(	'title_ro' 	=> 'ROBINETE CU SERTAR PANA PARALEL EXPANDABIL',
					'title_en' 	=> 'PARALLEL EXPANDING GATE VALVES',
					'link_ro' 	=> 'robinete-sertar-pana-paralel-expandabil',
					'link_en' 	=> 'parallel-expanding-gate-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 161,
				),	
	163 => array(	'title_ro' 	=> 'ROBINETE CU SERTAR PANA PENTRU SLAM',
					'title_en' 	=> 'SLURRY GATE VALVES',
					'link_ro' 	=> 'robinete-sertar-pana-slam',
					'link_en' 	=> 'slurry-gate-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 161,
				),	
	164 => array(	'title_ro' 	=> 'DISPOZITIVE DE REGLARE CU DUZE',
					'title_en' 	=> 'CHOKE VALVES',
					'link_ro' 	=> 'dispozitive-reglare-duze',
					'link_en' 	=> 'choke-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 161,
				),	
	165 => array(	'title_ro' 	=> 'SAPE DE FORAJ CU ROLE',
					'title_en' 	=> 'ROLE CONNER BITS',
					'link_ro' 	=> 'sape-foraj-role',
					'link_en' 	=> 'role-conner-bits',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 161,
				),	
	166 => array(	'title_ro' 	=> 'SAPE DE FORAJ DE INTERVENTIE',
					'title_en' 	=> 'WELL WORKOVER BITS',
					'link_ro' 	=> 'sape-foraj-interventie',
					'link_en' 	=> 'well-workover-bits',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 161,
				),	
				
	121	=> array(	'title_ro' 	=> 'RACORDURI SI ACCESORII',
					'title_en' 	=> 'JOINTS AND ACCESSORIES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	122	=> array(	'title_ro' 	=> 'COMPENSATORI DE MONTAJ',
					'title_en' 	=> 'DISMANTLING JOINTS',
					'link_ro' 	=> 'compensatori-montaj',
					'link_en' 	=> 'dismantling-joints',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 121,
				),
	123	=> array(	'title_ro' 	=> 'FLANSE OTEL',
					'title_en' 	=> 'CARBON STEEL FLANGES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 121,
				),
	124	=> array(	'title_ro' 	=> 'FLANSE LIBERE',
					'title_en' 	=> 'LOOSE FLANGES',
					'link_ro' 	=> 'flanse-libere-otel',
					'link_en' 	=> 'loose-flanges-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 123,
				),
	125	=> array(	'title_ro' 	=> 'FLANSE PLATE',
					'title_en' 	=> 'FLAT FLANGES',
					'link_ro' 	=> 'flanse-plate-otel',
					'link_en' 	=> 'flat-flanges-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 123,
				),
	126	=> array(	'title_ro' 	=> 'FLANSE OARBE',
					'title_en' 	=> 'BLIND FLANGES',
					'link_ro' 	=> 'flanse-oarbe-otel',
					'link_en' 	=> 'blind-flanges-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 123,
				),
	127	=> array(	'title_ro' 	=> 'FLANSE CU GAT',
					'title_en' 	=> 'NECK FLANGES',
					'link_ro' 	=> 'flanse-gat-otel',
					'link_en' 	=> 'neck-flanges-carbon-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 123,
				),
	128	=> array(	'title_ro' 	=> 'FLANSE INOX',
					'title_en' 	=> 'STAINLESS STEEL FLANGES',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 2,
					'parent'	=> 121,
				),
	129	=> array(	'title_ro' 	=> 'FLANSE LIBERE',
					'title_en' 	=> 'LOOSE FLANGES',
					'link_ro' 	=> 'flanse-libere-inox',
					'link_en' 	=> 'loose-flanges-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 128,
				),
	130	=> array(	'title_ro' 	=> 'FLANSE PLATE',
					'title_en' 	=> 'FLAT FLANGES',
					'link_ro' 	=> 'flanse-plate-inox',
					'link_en' 	=> 'flat-flanges-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 128,
				),
	131	=> array(	'title_ro' 	=> 'FLANSE OARBE',
					'title_en' 	=> 'BLIND FLANGES',
					'link_ro' 	=> 'flanse-oarbe-inox',
					'link_en' 	=> 'blind-flanges-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 128,
				),
	132	=> array(	'title_ro' 	=> 'FLANSE CU GAT',
					'title_en' 	=> 'NECK FLANGES',
					'link_ro' 	=> 'flanse-gat-inox',
					'link_en' 	=> 'neck-flanges-stainless-steel',
					'clickable' => true,
					'level' 	=> 3,
					'parent'	=> 128,
				),
				
	141	=> array(	'title_ro' 	=> 'FITINGURI',
					'title_en' 	=> 'FITTINGS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	142	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU SERTAR',
					'title_en' 	=> 'GATE VALVES',
					'link_ro' 	=> 'fitinguri-robinete-inchidere-sertar',
					'link_en' 	=> 'fittings-gate-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 141,
				),
				
	143	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU VENTIL',
					'title_en' 	=> 'GLOBE VALVES',
					'link_ro' 	=> 'fitinguri-robinete-inchidere-ventil',
					'link_en' 	=> 'fittings-globe-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 141,
				),
	144	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU SFERA',
					'title_en' 	=> 'BALL VALVES',
					'link_ro' 	=> 'fitinguri-robinete-inchidere-sfera',
					'link_en' 	=> 'fittings-ball-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 141,
				),
	145	=> array(	'title_ro' 	=> 'ROBINETE INCHIDERE CU CLAPA',
					'title_en' 	=> 'SWING CHECK VALVES',
					'link_ro' 	=> 'fitinguri-robinete-inchidere-clapa',
					'link_en' 	=> 'fittings-swing-check-valves',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 141,
				),
	146	=> array(	'title_ro' 	=> 'FILTRE Y',
					'title_en' 	=> 'Y STRAINERS',
					'link_ro' 	=> 'fitinguri-filtre-y',
					'link_en' 	=> 'fittings-y-strainers',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 141,
				),
				
	150	=> array(	'title_ro' 	=> 'ACTUATOARE',
					'title_en' 	=> 'ACTUATORS',
					'link_ro' 	=> '',
					'link_en' 	=> '',
					'clickable' => false,
					'level' 	=> 1,
					'parent'	=> 0,
				),
	151	=> array(	'title_ro' 	=> 'ACTUATOARE ELECTRICE',
					'title_en' 	=> 'ELECTRIC ACTUATORS',
					'link_ro' 	=> 'actuatoare-electrice',
					'link_en' 	=> 'electric-actuators',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 150,
				),
	152	=> array(	'title_ro' 	=> 'ACTUATOARE PNEUMATICE',
					'title_en' 	=> 'PNEUMATIC ACTUATORS',
					'link_ro' 	=> 'actuatoare-pneumatice',
					'link_en' 	=> 'pneumatic-actuators',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 150,
				),
	153	=> array(	'title_ro' 	=> 'ACTUATOARE HIDRAULICE',
					'title_en' 	=> 'HYDRAULIC ACTUATORS',
					'link_ro' 	=> 'actuatoare-hidraulice',
					'link_en' 	=> 'hydraulic-actuators',
					'clickable' => true,
					'level' 	=> 2,
					'parent'	=> 150,
				),
);
